version: '3.8'

volumes:
  pg_project_notebook:
  kafka_data:
  zookeeper_data:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=notebook
    volumes:
      - pg_project_notebook:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

  app:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - pg_db
      - kafka
    environment:
      DEEPSEEK_API_KEY: 'DEEPSEEK_API_KEY'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://pg_db:5432/notebook'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
      JAVA_OPTS: '-Xmx512m'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
    ports:
      - "127.0.0.1:2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "127.0.0.1:9092:9092"
      - "127.0.0.1:29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data