version: '3.1'

volumes:
  pg_project_notebook:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=notebook
    volumes:
      - pg_project_notebook:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
  app:
    restart: always
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - pg_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://pg_db:5432/notebook'
      JAVA_OPTS: '-Xmx512m'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1