version: '3'

volumes:
  pg_project_notebook:
  minio_data:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=notebook
    volumes:
      - pg_project_notebook:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

  app:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - pg_db
      - minio
    environment:
      DEEPSEEK_API_KEY: 'DEEPSEEK_API_KEY'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://pg_db:5432/notebook'
      JAVA_OPTS: '-Xmx512m'
      MINIO_URL: 'http://minio:9000'
      MINIO_ACCESS_KEY: 'minioadmin'
      MINIO_SECRET_KEY: 'minioadmin'
      MINIO_BUCKET: 'subtitles'

  minio:
    image: minio/minio
    restart: always
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"